# Generated by Django 3.0.2 on 2020-03-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200311_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='direction',
            field=models.BooleanField(default=None),
        ),
    ]
