# Generated by Django 3.0.2 on 2020-03-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200311_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='direction',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=15, null=True),
        ),
    ]
